---
output:
  html_document:
        theme: readable
editor_options: 
  chunk_output_type: console
---

# Pain killer experiment

Imagine that we have tested the effect of weak painkillers in a randomized controlled trial.

The setup was simple:

We randomly divided people into two group: "Placebo" and "Drug".

First we gave them a small electric shock and they reported the pain level they experienced (0-100). 

Then they got a pill (placebo pill or active pill).

After waiting for 15 minutes, we gave them another small electric shock and they reported the pain level they experienced (0-100).

```{r message=FALSE, warning=FALSE}

library(tidyverse)

df <- read_tsv(file = "t2.dataset.pain_experiment.tsv")

```

>Q2.1 How many individuals were analyzed in this dataset?

>Q2.2 How many placebo pills did we give out?

>Q2.3 What was the mean change in pain level (change = After-Before) in the placebo group?

>Q2.4 What was the mean change in pain level (change = After-Before) in the drug group?


>Q2.5 Test if the treatment reponse is different from 0 (no response) in the Placebo group, report the p value (two tailed test).

>Q2.6 Test if the treatment reponse in the Drug group is different than in the Placebo group. Report the p value (two tailed test).


>Q2.7 How large a proportion of all individuals had a pain level > 90 before treatment? 

Hint: Proportion is a number in the range [0;1]

Now we define a strong response as a decrease in pain level > 10.

>Q2.8 How large a proportion of individuals in the placebo group showed a strong reponse?

>Q2.9 How large a proportion of individuals in the drug group showed a strong reponse?


